# Site settings
title: Óscar de Arriba - odarriba.dev # site title
description: >- # site description
  Learnings, thoughts and experiments from an Elixir software developer that also enjoys DevOps.
lang: en-US # default lang
timezone: Europe/Madrid # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Óscar de Arriba
  bio: >-
    Learnings, thoughts and experiments from an Elixir software developer that also enjoys DevOps, meet him @ <a href="https://github.com/odarriba" target="_blank" rel="noopener">github</a> or <a href="https://x.com/odarriba" target="_blank" rel="noopener">x.com</a>.
  avatar: /assets/img/avatar.webp

# URL settings
url: "https://odarriba.dev"
baseurl:
permalink: /:title/
google_analytics:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 20

# Build settings
sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
