# Site settings
title: Óscar de Arriba - odarriba.dev
description: >-
  Learnings, thoughts and experiments from an Elixir software developer that also enjoys DevOps.
lang: en-US
timezone: Europe/Madrid
image: assets/img/og-image.jpeg
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Óscar de Arriba
  bio: >-
    Learnings, thoughts and experiments from an Elixir software developer that also enjoys DevOps.
  avatar: /assets/img/avatar.webp
  links:
    - name: GitHub
      url: https://github.com/odarriba
      icon: fab fa-github
    - name: Twitter
      url: https://x.com/odarriba
      icon: fab fa-x-twitter
    - name: Bluesky
      url: https://bsky.app/profile/odarriba.dev
      icon: fab fa-bluesky
    - name: LinkedIn
      url: https://www.linkedin.com/in/oscardearriba
      icon: fab fa-linkedin

# URL settings
url: "https://odarriba.dev"
baseurl:
permalink: /:title/
google_analytics:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 20

# Build settings
sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
